# Generated by Django 4.2.5 on 2024-11-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kind_clothes',
            fields=[
                ('ID_KIND', models.AutoField(primary_key=True, serialize=False)),
                ('NAME_KIND_CLOTHES', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'KIND_CLOTHES',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('ID_SEASON', models.AutoField(primary_key=True, serialize=False)),
                ('NAME_SEASON', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'SEASON',
            },
        ),
    ]
