# Generated by Django 4.2.5 on 2024-11-24 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('ID_CLOTHES', models.AutoField(primary_key=True, serialize=False)),
                ('COLOR', models.CharField(max_length=255)),
                ('BRAND', models.CharField(max_length=255)),
                ('MATERIAL', models.CharField(max_length=255)),
                ('IMAGE_CLOTHES', models.ImageField(upload_to='media/clothes')),
                ('KIND_CLOTHES_FK', models.ForeignKey(db_column='KIND_CLOTHES_FK', on_delete=django.db.models.deletion.CASCADE, to='clothes.kind_clothes')),
                ('SEASON_FK', models.ForeignKey(db_column='SEASON_FK', on_delete=django.db.models.deletion.CASCADE, to='clothes.season')),
            ],
            options={
                'db_table': 'CLOTHES',
            },
        ),
    ]
