# Generated by Django 4.2.5 on 2024-11-24 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_clothes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='IMAGE_CLOTHES',
            field=models.ImageField(upload_to='clothes'),
        ),
    ]
