# Generated by Django 4.2.5 on 2024-11-25 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clothes', '0003_alter_clothes_image_clothes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('ID_OUTFIT', models.AutoField(primary_key=True, serialize=False)),
                ('NAME_OUTFIT', models.CharField(max_length=255)),
                ('DATE_SCHEDULED', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'OUTFIT',
            },
        ),
        migrations.CreateModel(
            name='OutfitClothes',
            fields=[
                ('ID_OUTFITCLOTHES', models.AutoField(primary_key=True, serialize=False)),
                ('DATE', models.DateField(auto_now_add=True)),
                ('ID_CLOTHES_FK', models.ForeignKey(db_column='ID_CLOTHES_FK', on_delete=django.db.models.deletion.CASCADE, to='clothes.clothes')),
                ('ID_OUTFIT', models.ForeignKey(db_column='ID_OUFIT_FK', on_delete=django.db.models.deletion.CASCADE, to='outfits.outfit')),
            ],
            options={
                'db_table': 'OUTFITXCLOTHES',
                'unique_together': {('ID_OUTFIT', 'ID_CLOTHES_FK')},
            },
        ),
        migrations.AddField(
            model_name='outfit',
            name='CLOTHES_PARAM',
            field=models.ManyToManyField(through='outfits.OutfitClothes', to='clothes.clothes'),
        ),
        migrations.AddField(
            model_name='outfit',
            name='ID_SEASON_FK',
            field=models.ForeignKey(db_column='ID_SEASON_FK', on_delete=django.db.models.deletion.CASCADE, to='clothes.season'),
        ),
    ]
